# Generated by Django 4.1.1 on 2022-09-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('money', models.BigIntegerField(null=True)),
                ('person_type', models.CharField(choices=[('physical', 'Jismoniy shaxs'), ('juridic', 'Yuridik shaxs')], max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('processing', 'Moderatsiyada'), ('complated', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('degree', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'phd')], max_length=50, null=True)),
                ('contract_money', models.BigIntegerField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='backend.university')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.BigIntegerField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships', to='backend.sponsor')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='backend.student')),
            ],
            options={
                'verbose_name': 'Sponsorship',
                'verbose_name_plural': 'Sponsorships',
            },
        ),
    ]
