# Generated by Django 4.1.1 on 2022-09-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contract_money',
            new_name='contract',
        ),
    ]
